---
title: "ICES_datras_analysis_v2"
author: "Jo-Hannes Nowé"
date: "2025-10-17"
output: html_document
execute:
  echo: false
  warning: false
  message: false
params:
  species: "Gadus morhua"
---

```{r loading-packages}
library(sf)
library(terra)
library(dplyr)
library(ncdf4)
library(cmocean)
library(ggplot2)
```



Loading the new study area shapefile

```{r shapefile}
study_area <- st_read(file.path("data",
                                "study_area",
                                "20250912_10x10km_grid.shp"))
r <- rast(x = terra::vect(study_area), resolution = 10000)
v <- rasterize(study_area, r, field = runif(14400))
plot(v)
```
Loading the newly calculated data.
```{r load-data}
load(file.path("data",
               "CPUE_km2_2015_2024.RData")) #df
catch_all<- df %>%
  dplyr::select(Latitude = HaulLat, #Take this or HaulLat? Or mean of these?
                Longitude = HaulLong,
                Year, Month, SpeciesName, Catch = CPUE_number_per_km2)%>%
  dplyr::mutate(quarter = lubridate::quarter(Month))%>%
  dplyr::filter(SpeciesName == params$species)
```

```{r combinations}
#Define all quarter-year combinations
q_yr_combo <- expand.grid(quarter = unique(catch_all$quarter),
            Year = unique(catch_all$Year)) %>%
  arrange(Year, quarter)
```

```{r raster_function}
source(file.path("functions",
                 "calculate_mean.R"))
```

```{r qyear}
source(file.path("functions",
                 "qyear_mean.R"))
rasters_mean <- qyear_mean(raster_grid = r, 
                          q_yr_combo = q_yr_combo,
                          catch_df = catch_all)
raster_q1 <- rasters_mean$q1
raster_q3 <- rasters_mean$q3
```

```{r plot-raster}
source(file.path("functions",
                 "plot_raster.R"))
plot_raster(raster_q1, upper_limit = 100, plot_title = paste(params$species,"Q1 mean catch"))
plot_raster(raster_q3, upper_limit = 100, plot_title = paste(params$species,"Q3 mean catch"))
```

```{r mask-raster}
source(file.path("functions",
                 "mask_raster.R"))
q1_masked <- mask_raster(raster_q1, threshold = 0.90)
q3_masked <- mask_raster(raster_q3, threshold = 0.90)
plot_raster(q1_masked, upper_limit = 100, plot_title = paste(params$species,"Q1 masked mean catch"))
plot_raster(q3_masked, upper_limit = 100, plot_title = paste(params$species,"Q3 masked mean catch"))
```


```{r core-areas}
source(file.path("functions",
                 "core_areas.R"))
threshold_list <- c(0.5,0.6,0.7,0.8)
for(thr in threshold_list){
core_area_q1 <- core_areas(q1_masked, threshold = thr)
core_area_q3 <- core_areas(q3_masked, threshold = thr)
plot_raster(core_area_q1, upper_limit = 100, plot_title = paste(params$species,"Q1 core areas, threshold:", thr))
plot_raster(core_area_q3, upper_limit = 100, plot_title = paste(params$species,"Q3 core areas, threshold:", thr))
}
```

```{r specific-core-areas}
threshold <- 0.6
core_area_q1 <- core_areas(q1_masked, threshold = threshold)
core_area_q3 <- core_areas(q3_masked, threshold = threshold)
plot_raster(core_area_q1, upper_limit = 100, plot_title = paste(params$species,"Q1 core areas, threshold:", threshold))
plot_raster(core_area_q3, upper_limit = 100, plot_title = paste(params$species,"Q3 core areas, threshold:", threshold))
```

```{r}
source("functions/plot_consistent_core.R")
plot_consistent_core(core_area_q1, species = "Cod", quarter = "1")
plot_consistent_core(core_area_q3, species = "Cod", quarter = "3")
```

