---
title: "ICES_datras_analysis_v2"
author: "Jo-Hannes Nowé"
date: "2025-10-17"
format:
  html:
    self-contained: true
    embed-resources: true
    fig-format: png
    code-fold: false
execute:
  echo: false
  warning: false
  message: false
params:
  species: "Gadus morhua"
  group: "fish"
  plot_limit: 100
  years_mask: 0.0
  consistent_thr: 0.8 # grid cells above 50% cumulative sum are considered core areas for a given year
  idp_value: 1 # higher number corresponds to decreasing importance of distant points
  max_distance: 65000 
---

```{r loading-packages}
library(sf)
library(terra)
library(dplyr)
library(ncdf4)
library(cmocean)
library(ggplot2)
library(here)
library(gstat)
library(patchwork)
```
Parameters chosen for this run:
```{r}
#Chosen parameters for this run
print(paste("species:",params$species))
print(paste("group:",params$group))
print(paste("plot_limit:",params$plot_limit))
print(paste("years_mask:",params$years_mask))
print(paste("consistent_thr:",params$consistent_thr))
print(paste("idp_value:",params$idp_value))
print(paste("max_distance:", params$max_distance))
```


Loading the new study area shapefile

```{r}
study_area <- st_read(here("data",
                                "study_area",
                                "20250912_10x10km_grid.shp"))
r <- rast(x = terra::vect(study_area), resolution = 10000)
v <- rasterize(study_area, r, field = runif(14400))
plot(v)
```
Loading the newly calculated data.
```{r}
load(here("data",paste0("CPUE_km2_2015_2024_",params$group,".RData"))) #df depends on group
catch_all<- df %>%
  dplyr::select(Latitude = HaulLat, #Take this or HaulLat? Or median of these?
                Longitude = HaulLong,
                Year, Month, SpeciesName, Catch = CPUE_number_per_km2)%>%
  dplyr::mutate(quarter = lubridate::quarter(Month))%>%
  dplyr::filter(SpeciesName == params$species)%>%
  st_as_sf(coords = c("Longitude", "Latitude"),crs= 4326)%>%
  st_transform(3035)%>%
  dplyr::filter(!is.na(Catch))
```

```{r}
#Define all quarter-year combinations
q_yr_combo <- expand.grid(quarter = unique(catch_all$quarter),
            Year = unique(catch_all$Year)) %>%
  arrange(Year, quarter)
```

```{r raster_function}
source(here("functions",
                 "calculate_interpolation.R"))
```

```{r}
source(here("functions",
                 "qyear_interpolation.R"))
rasters_interpolation <- qyear_interpolation(raster_grid = v, 
                          q_yr_combo = q_yr_combo,
                          catch_df = catch_all,
                          idp_value = params$idp_value,
                          max_distance = params$max_distance)
raster_q1 <- rasters_interpolation$q1
raster_q3 <- rasters_interpolation$q3
```

```{r}
source(here("functions",
                 "plot_raster.R"))
plot_raster(raster_q1, upper_limit = params$plot_limit, plot_title = paste(params$species), plot_subtitle = "Q1 interpolated catch", save_path = here(paste0("outputs/png/interpolated_catch_yearly/", params$species, "_q1_interpolated_yearly.png")))
plot_raster(raster_q3, upper_limit = params$plot_limit, plot_title = paste(params$species), plot_subtitle = "Q3 interpolated catch", save_path = here(paste0("outputs/png/interpolated_catch_yearly/", params$species, "_q3_interpolated_yearly.png")))

#to check values of each interpolated raster:
# terra::plot(raster_q1[["2022"]])
```

```{r}
source(here("functions",
                 "core_areas.R"))
threshold_list <- c(0.5,0.6,0.7,0.8)
for(thr in threshold_list){
core_area_q1 <- core_areas(raster_q1, threshold = thr)
core_area_q3 <- core_areas(raster_q3, threshold = thr)

source(here("functions",
                 "plot_raster_binary.R"))

print(plot_raster_binary(core_area_q1, plot_title = params$species, plot_subtitle = paste0("Q1 core areas, threshold:", thr)))

print(plot_raster_binary(core_area_q3, plot_title = params$species, plot_subtitle = paste0("Q3 core areas, threshold:", thr)))
}
```

```{r specific-core-areas}
source(here("functions",
                 "core_areas.R"))

threshold <- params$consistent_thr
core_area_q1 <- core_areas(raster_q1, threshold = threshold)
core_area_q3 <- core_areas(raster_q3, threshold = threshold)

source(here("functions",
                 "plot_raster_binary.R"))

plot_raster_binary(core_area_q1, plot_title = params$species, plot_subtitle = paste0("Q1 core areas, threshold:", threshold) ,save_path = here(paste0("outputs/png/core_areas_yearly/", params$species,"_",threshold,"_q1_core_areas_yearly.png")))

plot_raster_binary(core_area_q3, plot_title = paste(params$species), plot_subtitle = paste0("Q3 core areas, threshold:", threshold), save_path = here(paste0("outputs/png/core_areas_yearly/", params$species,"_",threshold,"_q3_core_areas_yearly.png")))
```

```{r consistent-core}
source(here("functions",
            "plot_consistent_core.R"))
plot_consistent_core(core_area_q1, species = params$species, quarter = "1", shp= paste0(stringr::str_to_lower(params$species)%>%
  stringr::str_replace(" ","_"),"_q1_spawning_imr.shp"),save_path = here(paste0("outputs/png/consistent_core/", params$species,"_",threshold,"_q1_consistent_core_areas_yearly.png")))

plot_consistent_core(core_area_q3, species = params$species, quarter = "3",shp= paste0(stringr::str_to_lower(params$species)%>%
  stringr::str_replace(" ","_"),"_q3_spawning_imr.shp"),save_path = here(paste0("outputs/png/consistent_core/", params$species,"_",threshold,"_q3_consistent_core_areas_yearly.png")))
```

```{r scoring}
source(here("functions",
            "scoring_raster.R"))
p1= scoring_raster(core_area_q1, species = params$species,
               quarter = "1",
               shp= paste0(stringr::str_to_lower(params$species)%>%
  stringr::str_replace(" ","_"),"_q1_spawning_imr.shp"), plot_title =params$species, save_path = here(paste0("outputs/png/scored_raster/", params$species,"_",threshold,"_q1_scored_raster.png")))

p3 = scoring_raster(core_area_q3, species = params$species,
               quarter = "3",
               shp =paste0(stringr::str_to_lower(params$species)%>%
  stringr::str_replace(" ","_"),"_q3_spawning_imr.shp"), save_path = here(paste0("outputs/png/scored_raster/", params$species,"_",threshold,"_q3_scored_raster.png")))

source(here("functions",
            "combine_plots.R"))

combine_plots(species = params$species, save_path = here(paste0("outputs/png/scored_raster/", params$species,"_",threshold,"_scored_raster.png")))

```


